generate-repology-metadata: add urls to patches and build recipe to generated json
termux/repology-metadata pull request #3
Opened 2022-02-19 15:46 UTC by Grimler91

And add helper functions for writing json objects, to make it easier to extend and maintain the script.

Fixes https://github.com/termux/repology-metadata/issues/2.

Example packages.json: https://grimler.se/files/packages.json

2022-02-19 15:48 UTC, Grimler91 commented
Ping @AMDmi3, do you have any comments on the entries and format?

2022-02-19 16:09 UTC, thunder-coding requested changes

2022-02-19 16:09 UTC, thunder-coding commented on generate-repology-metadata.sh
> +	local patches=$(git ls-files --full-name "*.patch" "*.patch32" "*.patch64" "*.patch.beforehostbuild")
```suggestion
	local patches=$(git ls-files --full-name "*.patch" "*.patch32" "*.patch64" "*.patch.beforehostbuild" "*.diff" "*.patch.txt")
```

2022-02-19 16:09 UTC, thunder-coding commented on generate-repology-metadata.sh
> +
Would make sense to add a condition to confirm whether it is really a valid GitHub repo URL.

2022-02-19 17:29 UTC, Grimler91 commented on generate-repology-metadata.sh
> +	local patches=$(git ls-files --full-name "*.patch" "*.patch32" "*.patch64" "*.patch.beforehostbuild")
Thanks for the review! Will fix, will rename all .patch.txt to .diff, as having different suffix'es seem unnecessary

2022-02-19 17:30 UTC, Grimler91 commented on generate-repology-metadata.sh
> +
Sure, can match a regex pattern instead and error if not match!

2022-02-22 20:57 UTC, Grimler91 commented
Accidentally pushed to master, but comments have been addressed, url is verified that it is a github url, and .diff are included in patch list

2022-02-22 20:57 UTC, closed without merging

2022-02-22 21:08 UTC, Grimler91 commented
Hmm, no, I pushed the wrong branch to master. Will have to force push to fix this